services:
  browserquest-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: browserquest
    expose:
      - "8000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:stable
    container_name: browserquest-nginx
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - browserquest-server
