services:
  browserquest-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: browserquest
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: browserquest-nginx
    ports:
      - "80:80"
    depends_on:
      - browserquest-server
